version: 2
updates:

  # Check for updates to GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      github-actions:
        patterns:
          - "*"
  - package-ecosystem: "gitsubmodule"
    directory: "/"        
    schedule:
      interval: "daily"
    target-branch: "main"
    allow:
      - dependency-name: "half"
      - dependency-name: "HIPIFY"
      - dependency-name: "rccl"
      - dependency-name: "rccl-tests"
      - dependency-name: "rocprof-trace-decoder"
      - dependency-name: "rocm-cmake"
      - dependency-name: "rocm-systems"
    reviewers:
      - "ScottTodd"
      - "marbre"
    open-pull-requests-limit: 10
