version: 2
updates:

  # Check for updates to GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      github-actions:
        patterns:
          - "*"
  - package-ecosystem: "gitsubmodule"
    directory: "/"
    schedule:
      # 2:00 AM PST â†’ 10:00 UTC
      interval: "cron"
      cronjob: "0 10 * * *"
    target-branch: "main"
    allow:
      - dependency-name: "rocm-systems"
    reviewers:
      - "ScottTodd"
      - "marbre"
      - "geomin12"
    open-pull-requests-limit: 10
