# hipTensor
[components.dbg."ml-libs/hipTensor/stage"]
optional = true

[components.dev."ml-libs/hipTensor/stage"]
optional = true
include = [
  "include/hipTensor/*",
]

[components.lib."ml-libs/hipTensor/stage"]
optional = true

[components.test."ml-libs/hipTensor/stage"]
optional = true
include = [
  # Samples
  "bin/simple_*",
  # Tests
  "bin/*_test*",
]
